//
//  DetailAsiaVC.swift
//  Learning Countries
//
//  Copyright © 2019 Eduard Sinyakov. All rights reserved.
//

import Foundation
import UIKit

//TODO: Возможно, сделать не от BasedVC
class DetailAsiaVC: UIViewController {
    
    var labelText = String()
    var imageName = String()
    // var description = //TODO: Бать значение из словаря по ключу "название страны"
    
    @IBOutlet weak var detailTextView: UITextView!
    @IBOutlet weak var detailLabel: UILabel!
    @IBOutlet weak var detailImageView: UIImageView!
    
    
    //MARK: - viewDidLoad
    override func viewDidLoad() {
        super.viewDidLoad()
        
        //MARK: - get values from EuropeVC and set in current vc
        detailImageView.image               = UIImage(named: imageName)
        detailImageView.contentMode         = .scaleToFill
        detailImageView.layer.borderWidth   = 1
        detailImageView.layer.cornerRadius  = 20
        detailImageView.layer.borderColor   = #colorLiteral(red: 0.8039215803, green: 0.8039215803, blue: 0.8039215803, alpha: 1)
        detailImageView.clipsToBounds       = true
        detailLabel.text                    = labelText
        
        
        
        //MARK: Texts
        if imageName == "Brunei" {
            detailTextView.text = "Brunei Darussalam (Malay: Negara Brunei Darussalam, also known as the Brunei Islamic monarchy; Negara means “country”, while Darussalam means “state of peace”, meaning vigilance and stability), Referred to as Brunei, it is a monarchy. Brunei is located in southeastern Asia, northwest of Kalimantan Island, north of China's South China Sea, bordering Sarawak State of Malaysia on the southeast and west, and separated into two parts by the Lin Meng of Sarawak. The coastline is about 162 kilometers long and has 33 islands with a total area of 5,765 square kilometers. Tropical rain forest climate. Brunei is called mud. In the middle of the 14th century, Islam was introduced and the Sultanate was established. In 1888 he became a British protectorate, occupied by Japan in 1941, and in 1946 the British resumed control of Brunei. Completely independent on January 1, 1984. Brunei is a country with crude oil and natural gas as its main economic pillars, accounting for 50% of the country's gross domestic product. In Southeast Asia, oil reserves and production rank second only to Indonesia. In 2016, the per capita GDP was 26,939 US dollars, ranking 26th in the world."
        } else if imageName == "Cambodia" {
            detailTextView.text = "The Kingdom of Cambodia, commonly known as Cambodia, formerly known as Khmer, is located in the Indo-China Peninsula, bordering Thailand in the west and northwest, bordering Laos in the northeast, bordering Vietnam in the east and southeast, and facing the Gulf of Siam in the south. The territory of Cambodia is a dish basin, surrounded by hills and mountains on three sides, and a vast and rich plain in the middle, accounting for more than three-quarters of the country's total area. There are the Mekong River and the largest freshwater lake in Southeast Asia - Tonle Sap Lake (also known as Phnom Penh Lake), the capital of Phnom Penh. Cambodia has a population of about 15 million and Khmer accounts for 80% of the total population. Chinese overseas Chinese are about 1 million. Cambodia is an ancient country with a long history of civilization. It established a unified kingdom as early as the 1st century AD. Since the 1970s, Cambodia has experienced a long war. In 1993, with the establishment of the Cambodian national authorities and the realization of national reconciliation, Cambodia entered a new era of peace and development. Cambodia is a member of the Association of Southeast Asian Nations. The economy is dominated by agriculture and its industrial base is weak. It is one of the least developed countries in the world."
        } else if imageName == "People's_Republic_of_China" {
            detailTextView.text = "People's Republic of China, referred to as China, was established on October 1, 1949. It is located in the eastern part of Asia and on the west coast of the Pacific Ocean. It is a socialist country led by the working class and based on the people's democratic dictatorship. With the five-star red flag as the national flag and the March of the Volunteers as the national anthem, the national emblem is the national flag, Tiananmen, gears and wheat ears. The common language is Mandarin and standardized Chinese characters. The capital Beijing is a Han nationality and 56 ethnic groups. A unified multi-ethnic country.China has a land area of ​​about 9.6 million square kilometers, more than 18,000 kilometers of coastline on the eastern and southern continents, and more than 4.7 million square kilometers of water in the inland and frontier seas. There are more than 7,600 large and small islands in the sea, of which Taiwan Island is the largest with an area of ​​35,798 square kilometers. China is bordered by 14 countries and is adjacent to the eight countries. The provincial administrative division is divided into 23 provinces, 5 autonomous regions, 4 municipalities directly under the Central Government, and 2 special administrative regions. China is one of the oldest countries in the world, with a splendid culture and a glorious revolutionary tradition, and a world leader in world heritage. After the founding of New China in 1949, it entered the period of socialist revolution and construction. In 1956, it realized the transition to socialism. Since then, socialist construction has undergone twists and turns in exploration. After the end of the Cultural Revolution, reform and opening up were carried out, and along the path of socialism with Chinese characteristics, efforts were concentrated on socialist modernization. After a long period of hard work, socialism with Chinese characteristics has entered a new era. China is the most populous developing country in the world, ranking third in the world and the second largest economy in the world. It continues to be the largest contributor to world economic growth. In 2018, the total economic output exceeded 90 trillion yuan. China adheres to an independent foreign policy of peace. It is a permanent member of the UN Security Council and an important member of many international organizations. It is considered to be one of the potential superpowers."
        } else if imageName == "India" {
            detailTextView.text = "Republic of India (Hindi: भारत गणराज्य; English: Republic of India), referred to as India. Located in South Asia, it is the largest country in the South Asian subcontinent. The northeastern part of the territory borders Bangladesh, Nepal, Bhutan and China, the east is bordered by Myanmar, the southeast is across the sea from Sri Lanka, and the northwest is bordered by Pakistan. It faces the Bay of Bengal in the east and the Arabian Sea in the west, with a coastline of 5,560 kilometers. It is also a unified multi-ethnic country composed of more than 100 ethnic groups. The main ethnic group is the Hindustan, accounting for 46.3% of the country's total population. Ancient India was one of the four ancient civilizations. The Indus civilization was born in 2500 BC (mainly in Pakistan today). Around 1500 years ago, the Aryans in Central Asia entered the South Asian subcontinent, conquered the local ancient Indians, established some small slavery countries, and established the caste system. The Vedas began to develop into Brahmanism. In the 4th century BC, the Peacock Dynasty unified India and began to promote Buddhism and spread it outward. In the first 188 years, after the demise of the Peacock Empire, the masses were divided, the invasion of foreigners, and the rise of Hinduism and Islam. In 1600, the British invaded the Mughal Empire and established the East India Company. After 1757, it gradually became a British colony. In June 1947, the United Kingdom enacted the Mount Montaton Plan to implement the division of India and Pakistan. On August 15, the same year, the Indian Dominion was established. On January 26, 1950, the Republic was announced and became a member of the Commonwealth. India is the second most populous country in the world and one of the BRICS countries. India's economic industry is diversified, covering agriculture, crafts, textiles and services. Two-thirds of India's population still depends directly or indirectly on agriculture. In recent years, the service industry has grown rapidly and has become the most important exporter of software and financial services in the world. The world's largest exporter of generic drugs, the world's first overseas remittance. India is a developing country with extremely uneven distribution of social wealth. The caste system is more acute."
        } else if imageName == "Indonesia" {
            detailTextView.text = "Republic of Indonesia (Indonesian: Republik Indonesia, English: Republic of Indonesia), referred to as Indonesia (Indonesia). It is a Southeast Asian country and the capital is Jakarta. Connected with countries such as Papua New Guinea, East Timor and Malaysia. It is composed of about 17,508 islands and is part of the Malay archipelago. It is also the largest archipelago country in the world. Its territory spans Asia and Oceania. It is also known as the “land of thousands of islands” and is also a country with many volcanic earthquakes. The larger islands are Kalimantan, Sumatra, Irian, Sulawesi and Java.In the 13th and 14th centuries, a powerful empire was formed in Java, and at the end of the 16th century it became a Dutch colony. It was occupied by Japan in 1942. Independence in 1945, the Republic was established in August 1950. In 1963, he recovered West Irian, who was invaded by the Netherlands.Indonesia has a population of nearly 262 million (2019), second only to China, India and the United States, ranking fourth in the world. Indonesia is one of the founding countries of the Association of Southeast Asian Nations. It is also the largest economy in Southeast Asia and a member of the Group of 20 countries. Its aerospace technology is strong. Petroleum resources can achieve net exports. Indonesia was a member of the Organization of Petroleum Exporting Countries (1962~2009) and is re-joining the organization in the near future. The Indonesian Islands have been an important trading area since the 7th century."
        } else if imageName == "Japan" {
            detailTextView.text = "Japan (Japanese: にっぽんこく, にほんこく; English: Japan), referred to as Japan, located in East Asia, the country name means Sunrise Country, the territory consists of four major islands of Hokkaido, Honshu, Shikoku, Kyushu and more than 6,800 It consists of small islands with a total area of ​​378,000 square kilometers. The main ethnic group is the Yamato, universal Japanese, with a total population of about 126 million. The three major metropolitan areas in Japan are the Tokyo Metropolitan Area, the Osaka Metropolitan Area, and the Nagoya Metropolitan Area. Japan is an island country on the west coast of the Pacific. The East China Sea, the Yellow Sea, the Korean Strait, and the Sea of ​​Japan are facing each other, such as China, North Korea, and South Korea. It is a temperate maritime monsoon climate with mild and humid years. More plum rain in June, more typhoons in summer and autumn. In the middle of the 3rd century, Dahe Kingdom appeared in its territory. In 645, Japan learned from the Chinese Tang Dynasty and carried out major reforms. In the late 12th century, the Emperor's imperial power fell into the era of the shogunate. In the mid-1950s, the black ship incident forced Japan to abandon the lock-up policy and sign a series of unequal treaties. In 1868, Emperor Meiji returned to power, carried out the Meiji Restoration, established the Japanese Empire, quickly became a column of capitalist powers, and embarked on the path of militarism of aggression and expansion. He repeatedly invaded China, North Korea and other Asian countries. After the defeat of the Second World War, a new constitution was promulgated, from the emperor-made country to the parliamentary cabinet state with the emperor as the national symbol. Japan is a highly developed capitalist country, the third largest economy in the world, and a member of the G8. Its resources are scarce and extremely dependent on imports, and developed manufacturing is the backbone of the national economy. Research, aerospace, manufacturing, and education are among the highest in the world. In addition, the cultural industry led by animation and game industry and developed tourism are also important symbols. Japan is a world model in many aspects such as environmental protection and resource utilization. Its citizens generally have good education, living standards and national quality. Japanese traditional culture such as tea ceremony, flower path, and book path have been ."
        } else if imageName == "Laos" {
            detailTextView.text = "Lao People's Democratic Republic (Lao: ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ), referred to as Laos (Lao: ເມືອງລາວ). It is a landlocked country located in the northern part of the Indo-China Peninsula. It borders China in the north, Cambodia in the south, Vietnam in the east, Myanmar in the northwest, and Thailand in the southwest. It has a land area of ​​236,800 square kilometers and a population of 6.8 million (2015). The capital is Vientiane. Laos was called Nanzhang in the ancient times. During the reign of Emperor Yongzheng, he was attached to the Central Government of the Qing Dynasty in China and belonged to China. It was once part of the real kingdom of history. It was the southern palm of the 13th to 18th centuries. It was later invaded by Siam and Vietnam, and later invaded by France. In 1893, it became a French colony. In 1945, in 1975, the monarchy was abolished and the Republic was established. Laos joined the Association of Southeast Asian Nations in July 1997 and has established diplomatic relations with 138 countries. The socialist system is currently in place. The Lao People’s Revolutionary Party is the only political party in Laos. Laos is one of the least developed countries in the world. It is mainly based on agriculture. The industrial and service industries are weak in foundation and rich in water resources. It produces valuable wood such as teak and rosewood."
        } else if imageName == "Malaysia" {
            detailTextView.text = "Malaysia, referred to as Malaysia, is a federal state that elects monarchy, constitutional monarchy and parliamentary democracy. The capital city of Kuala Lumpur, the federal government administrative center Putrajaya. The country is divided into 13 states and 3 federal territories, covering a total area of ​​330,000 square kilometers. Located in Southeast Asia, Malaysia is divided into two parts, the East and West by the South China Sea, namely the Peninsula of Malaysia (West Malaysia) on the Malay Peninsula and the northern part of Kalimantan (East Malaysia). The total length of the national coastline is 4192 kilometers. Tropical rain forest climate. The average annual temperature in the mountainous areas of the interior is 22-28 °C, and the coastal plain is 25-30 °C. On August 31, 1957, Chief Minister Tunku Abdul Rahman announced the independence of Malayan United States; in 1963, Malayan United Confederacy formed Singapore with Singapore, Sabah and Sarawak (Singapore exit on August 9, 1965) . The Federal Government system in Malaysia closely follows the British Westminster parliamentary system. The highest representative of the country inside and outside is called the head of state, and the head of government is the prime minister (prime minister). Malaysia is a multi-ethnic, multicultural country. Although the official religion is Islam, the right to freedom of national religion is guaranteed by the Malaysian Constitution. Malaysia is a capitalist country whose economy has grown by leaps and bounds in the 1990s. It is one of the four tigers in Asia and has become a diversified emerging industrial country and a world emerging market economy in Asia. The state implements new economic policies that are preferred by Malays and indigenous peoples. Malaysia pursues an independent, neutral and non-aligned foreign policy. It is one of the founding members of ASEAN. It has established diplomatic relations with 132 countries and has 110 embassies and consulates in 84 countries. At the same time, it is a participating country of the Commonwealth, the Non-Aligned Movement, the Organization of Islamic Cooperation, the Asia-Pacific Economic Cooperation, and the Indian Ocean Alliance. The main military operations involved are the joint defense of five countries and UN peacekeeping operations.On May 9, 2018, the opposition camp hoped that the league won the general election and ended the 60-year rule of the ruling National Front."
        } else if imageName == "Mongolia" {
            detailTextView.text = "Mongolia (Mongolian: Монголулс, English: Mongolia), referred to as Mongolia. Located between the People's Republic of China and Russia, a landlocked country surrounded by the two countries, although Mongolia does not border the Kazakhstan border, its westernmost point to the easternmost point of Kazakhstan is only 38 kilometers. The capital and the largest city in the country is Ulaanbaatar, accounting for 45% of the country's total population.In Mongolian history, it was ruled by Xiongnu, Xianbei, Rouran, Turkic, and Qidan. In 1206, Genghis Khan established the Great Mongolia. In 1271, his grandson Kublai established the Yuan Dynasty. In 1368, after the fall of the Yuan Dynasty, the Mongols returned to the Mongolian steppe, and the conflict with the Ming Dynasty continued, such as the famous civil castle. In the 17th century, the Qing government of China unified the Mongolian ministries, and the entire territory of Mongolia was under the jurisdiction of the Chinese central government. In 1911, after the demise of the Qing Dynasty, Mongolia declared independence, but it was not internationally recognized until 1921, under the control of the Soviet Union, declared independence. In 1946, the Republic of China recognized its independence. In 1961, joining the United Nations began to gain recognition from the international community. After the drastic changes in Eastern Europe, a democratic revolution broke out in Mongolia. In 1992, a new constitution with a multi-party system was enacted. The country was changed to Mongolia and began to transition to a market economy. With a land area of ​​1,566,500 square kilometers, Mongolia is the 19th largest country in the world and the second largest landlocked country in the world after Kazakhstan. With a population of about 3 million, it is the country with the smallest population density in the world. Mongolia has less arable land and most of its land is covered by grasslands. There are many mountains in the north and west, and the Gobi desert in the south. About 30% of the population is engaged in nomadic or semi-nomadic. Mainly believe in Tibetan Buddhism, the main ethnic group is Mongolian, and there are also ethnic minorities such as Kazak and Tuva distributed in the west. The gross domestic product is 11.149 billion US dollars (2017). Joined the World Trade Organization in 1997."
        } else if imageName == "Myanmar" {
            detailTextView.text = "The Republic of the Union of Myanmar, referred to as Myanmar. It is a country in Southeast Asia and a member of the Association of Southeast Asian Nations. It is bordered by the Andaman Sea in the southwest, India and Bangladesh in the northwest, China in the northeast, Thailand and Laos in the southeast, and the capital of Naypyidaw. Myanmar is a long-established ancient civilization, formerly known as Hongshawa. After forming a unified country in 1044, he experienced four feudal dynasties: Bagan, Bago, Dongyu and Gongbang. Between 1824 and 1885, the British launched three wars of invasion of Burma and occupied Burma. In 1886, the United Kingdom classified Myanmar as a province of British India. On January 4, 1948, Myanmar declared independence from the Commonwealth and established the Union of Myanmar. In January 1974, it was renamed the Federal Socialist Republic of Myanmar. In July 1988, due to the deterioration of the economic situation, demonstrations broke out throughout Myanmar. On September 18 of the same year, the military headed by General Su Su, the Minister of National Defense, took over the political power and established the National Law and Order Restoration Council (renamed Myanmar National Peace and Development Committee in 1997), announcing the abolition of the Constitution and dissolving the People's Assembly and National authority. On September 23, 1988, the name of the country was changed from the Federal Socialist Republic of Myanmar to the Myanmar Federation. In May 2008, the new Constitution of the Republic of Myanmar was passed, providing for a presidential system. In 2010, Myanmar held a multi-party national election in accordance with the new constitution. On February 4, 2011, the Myanmar Parliament elected Wu Dengsheng as the first president of Myanmar. On March 15, 2016, the Federal Parliament of Myanmar elected Wu Tingjue as the first non-military president of Myanmar for more than half a century. Myanmar is one of the least developed countries in the world. It is mainly based on agriculture. The population engaged in agriculture is over 60%. The agricultural products include rice, wheat and sugar cane. On March 21, 2018, Myanmar President Wu Tingjue resigned."
        } else if imageName == "North_Korea" {
            detailTextView.text = "Democratic People's Republic of Korea (Korean: Democratic People's Republic of Korea), referred to as North Korea. It is a socialist country located in the northern part of the East Asian Peninsula. The ruling party is the Workers' Party of Korea and the capital of Pyongyang. The south and South Korea are separated by the demilitarized zone of the 38th and South Korea, and the north is bordered by the People's Republic of China and Russia. It faces the Bohai Sea in the west, faces the Shandong Peninsula across the sea, and faces the Sea of ​​Japan in the east. The Democratic People’s Republic of Korea was established on September 9, 1948, after the Second World War. The territory covers an area of ​​123,000 square kilometers and has a population of 25,610,672 (2018). The Korean nation/Korean nation is a single nation, and it is a Korean language. In 1958, North Korea declared that it had completed the socialist transformation of urban and rural production relations and established a socialist economic system. In 1970, it declared that socialist industrialization was realized. In May 1975, he became a full member of the Seventy-seventh Group and officially joined the Non-Aligned Movement in August of the same year. Joined the United Nations with South Korea on September 17, 1991. In July 2000, he joined the ASEAN Regional Forum (ARF). Established diplomatic relations with 163 countries (including the European Union). North Korea is the main policy of the main idea put forward by the first leader Kim Il Sung, and the North Korean Labor Party is governed by one party. Its political and economic system is dominated by the politics of the First Army and is a country that adheres to socialism. North Korea pursues a foreign policy of independence, peace, and friendship and advocates developing foreign relations in accordance with the principles of full equality, independence, mutual respect, non-interference in each other's internal affairs, and mutual benefit. In the military, it emphasizes strengthening the national strength under the guidance of the thought of the first army. North Korea has about 1.2 million soldiers and is the fifth largest number of armed forces in the world."
        } else if imageName == "Pakistan" {
            detailTextView.text = "Islamic Republic of Pakistan (Urdu: اسلامی جمہوریہ پاکستان, English: Islamic Republic of Pakistan), referred to as “Pakistan” (Pakistan), meaning “holy land”, “land of halal”. More than 95% of residents believe in Islam and are a multi-ethnic Islamic country. The national language is Urdu. Pakistan is located in the northwestern part of the South Asian subcontinent, with the Arabian Sea in the south, India in the east, the People's Republic of China in the northeast, the border with Afghanistan in the northwest, and Iran in the west. The coastline is 980 kilometers long. The southern part has a tropical climate and the rest has a subtropical climate. The capital, Islamabad, the former capital Karachi is the largest city. In 1857, the Mughal Empire (including India and Pakistan today) became a British colony and became part of British India. In June 1947, the United Kingdom enacted the Mount Montaton Plan to implement the division of India and Pakistan. On August 14 of the same year, he declared independence and became a Pakistani self-governing leader. On March 23, 1956, the Islamic Republic of Pakistan was established as a member of the Commonwealth. In 1971, the eastern part of the country was separated from Pakistan and the People's Republic of Bangladesh was established. Pakistan is a fast-growing developing country and a member of the World Trade Organization, the Organization of the Islamic Conference, the Group of 77, the Non-Aligned Movement, the Shanghai Cooperation Organization and the Commonwealth."
        } else if imageName == "Philippines" {
            detailTextView.text = "The Republic of the Philippines (Tagalog: Republika ng Pilipinas), referred to as the Philippines, is located in the Western Pacific and is a multi-ethnic archipelago in Southeast Asia with an area of ​​297,700 square kilometers and a population of 104.9 million (2017). The Filipinos' ancestors were immigrants from the Asian continent, and Sulu was established around the 14th century. In 1565 it became a Spanish colony. On June 12, 1898, independence was declared. After the American-American War in the same year, it became a US territory. From 1942 to 1945, it was occupied by Japan. After the Second World War, it was re-established as a US colony. On July 4, 1946, the Philippines gained independence. The Philippines is divided into three major island groups: Luzon, Visayas and Mindanao. There are more than 7,000 large and small islands. There are many ethnic and cultural diversity. It combines many customs of the East and West. The prehistoric Negrito may be the earliest in the Philippines. Residents, and then the migration of the nation gradually brought Malay culture, and with the development of religion and trade also brought Indian culture, Chinese culture and Islamic culture. The Philippines is a major member of ASEAN and one of the 24 member states of the Asia Pacific Economic Cooperation (APEC). The Philippines is one of the emerging markets of developing countries, emerging industrial countries and the world, but the gap between rich and poor is very large. Since independence, the Philippines has experienced several rapid economic growth. However, the political situation is often turbulent, the government is corrupt, and social unrest has become a major factor hindering its development. On March 16, 2018, the Philippines officially notified the United Nations of its decision to withdraw from the International Criminal Court. On March 17, 2019, the Philippines officially withdrew from the International Criminal Court."
        } else if imageName == "Singapore" {
            detailTextView.text = "The Republic of Singapore (English: Republic of Singapore), formerly known as Xinjiapo, Xingzhou or Xingdao, is not known as the Lion City. It is an island country in Southeast Asia, and the political system implements a parliamentary republic. Singapore's northern Johor Strait is adjacent to Malaysia, south across the Singapore Strait from Indonesia, and adjacent to the southern mouth of the Straits of Malacca. In addition to Singapore Island (88.5% of the country's total area), the country also includes 63 small islands. In the 8th century, Singapore was a sacred Buddha; the 14th century belonged to the Malacca Sultan dynasty founded by Bairimisula; the 18th-19th century belonged to the Kingdom of Johor. At the beginning of the 19th century, it was occupied by the British colonies; on February 15, 1942, Singapore was invaded by Japan; in 1963, it joined Malaysia; in 1965, Singapore officially became independent. Singapore is a multicultural immigrant country. Promoting racial harmony is the core policy of government governance. Singapore is known for its stable political situation, clean and efficient government, and is one of the most international countries in the world. Singapore is a developed capitalist country and is known as one of the “Asian Four Little Dragons”. Its economic model is called “state capitalism”. According to the 2018 Global Financial Centers Index (GFCI) ranking report, Singapore is the fourth largest international financial center after New York, London and Hong Kong [2]. Singapore is also one of Asia's important service and shipping centers, and was ranked fifth in the world's first-tier cities by GaWC [3-4]. Singapore is a member of the Association of Southeast Asian Nations (ASEAN) and one of the member economies of the World Trade Organization (WTO), The Commonwealth and the Asia Pacific Economic Cooperation (APEC)."
        } else if imageName == "South_Korea" {
            detailTextView.text = "Republic of Korea (Korean: Republic, Korea), referred to as South Korea. It is located in the southern part of East Asia's Korean Peninsula, with a total area of about 100,000 square kilometers (accounting for 45% of the Korean Peninsula). The main ethnic group is the Korean nation and GM Korean, with a total population of 51.47 million. The capital is Seoul. South Korea is surrounded by the sea on three sides, the Yellow Sea on the west, the Korean Strait on the southeast, the Sea of Japan on the east, and the North Korea on the north by the demilitarized zone of the 38th parallel. In 1910, the Korean peninsula became a Japanese colony. On August 15, 1945, Sun Yat-sen acquired independence. In August and September 1948, the Republic of Korea and the Democratic People’s Republic of Korea were established in the north and south of the Korean Peninsula on the 38th line of the North. The Korean War broke out in 1950. On July 27, 1953, according to the Korean Armistice Agreement, the two sides fought armistically. Since the 1960s, the South Korean government has implemented an export-led development economic strategy, creating a period of rapid economic growth known as the Hanjiang Miracle and becoming one of the Asian Four Little Dragons."
        } else if imageName == "Thailand" {
            detailTextView.text = "Kingdom of Thailand (Thai: English, The Kingdom of Thailand), referred to as Thailand (Thailand). It is a constitutional monarchy in Southeast Asia. Thailand is located in the central part of the Central South Peninsula. It borders the west and the north with Myanmar and the Andaman Sea. The northeast is Laos, the southeast is Cambodia, and the narrow peninsula to the south is connected to Malaysia. The old name of Siam in Thailand, on May 11, 1949, the Thai people used the name of their own nation to change Siam to Thai, mainly to take the meaning of freedom. Thailand implemented a free economic policy. In the 1990s, the economy developed rapidly and became one of the four tigers in Asia. However, it suffered a major setback in the 1998 economic crisis and then fell into recession and stagnation. It is one of the world's emerging industrial countries and the world's emerging market economies. Manufacturing, agriculture and tourism are the main sectors of the economy. Thailand is the only net exporter of food in Asia and one of the world's five largest exporters of agricultural products. The manufacturing industry such as the electronics industry is developing rapidly, and the industrial structure is changing. The automobile industry is the pillar industry. It is the Southeast Asian automobile manufacturing center and the largest automobile market in ASEAN. Thailand is one of the most famous tourist destinations in the world. Thailand is a country of Buddhism, and most Thais believe in the four-faced Buddha. Buddhists account for more than 90% of the country's population. Thailand is a member of the Association of Southeast Asian Nations and a founding member of the Association of Southeast Asian Nations, as well as a member of the Asia-Pacific Economic Cooperation, the Asia-Europe Meeting and the World Trade Organization."
        } else if imageName == "Vietnam" {
            detailTextView.text = "Vietnam, known as the Socialist Republic of Vietnam (English: Socialist Republic of Vietnam, Vietnamese: Cộng hòa Xã hội Chủ nghĩa Việt Nam), referred to as Vietnam (Vietnam), is a socialist country in Asia. It is located in the eastern part of the Indo-China Peninsula in Southeast Asia, bordering Guangxi and Yunnan in the north, and bordering Laos and Cambodia in the west. It has a narrow territory and covers an area of ​​about 330,000 square kilometers. It is adjacent to the South China Sea and has a coastline of more than 3,260 kilometers. It is a multi-ethnic country with the Jing people as the main body. . The name of Vietnam comes from the Qing Dynasty Jiaqing Emperor. Historically, northern Vietnam has long been a Chinese territory. In 968, it officially separated from China and established itself. After that, Vietnam experienced many feudal dynasties and continued to expand southward, but the dynasties were all Chinese vassal countries. After the middle of the 19th century, it gradually became a French colony. After the August 1945 revolution, Ho Chi Minh announced the establishment of the Democratic Republic of Vietnam. In 1976, he changed his name to the Socialist Republic of Vietnam. In 1986, reform and opening up began. In 2001, the 9th National Congress of the Communist Party of China decided to establish a socialist market economic system. The Communist Party of Vietnam is the only legitimate ruling party in the country. Vietnam is also a member of the Association of Southeast Asian Nations."
        }
        else if imageName == "Bangladesh" {
            detailTextView.text = "People's Republic of Bangladesh (Bengali: Gônôprôjatôntri Bangladesh, English: People's Republic Of Bangladesh), referred to as Bangladesh, South Asian countries, located in the north of the Bay of Bengal, a small part of the southeastern mountainous region is adjacent to Myanmar, and the east, west and north are adjacent to India. There are still a large number of enclaves on the northern border, with a total area of ​​147,570 square kilometers. In June 2015, India and Bangladesh reached a new border agreement. Bangladesh obtained 111 enclaves with a total area of ​​170 square kilometers. The residents within the enclave have been free to choose their nationality. The Bengali is one of the ancient peoples of the South Asian subcontinent. The earliest inhabitants of Bangladesh are Asians and Australians. In 1757, Bangladesh became a province of British India. After the partition of India and Pakistan in 1947, it belonged to Pakistan and was called East Pakistan. In 1971, he was independent from Pakistan. Most parts of Bangladesh have a subtropical monsoon climate, hot and humid. The river is densely paved, the river is developed, the rainy season is extremely prone to flooding, and tropical hurricanes often occur. The mine contains natural gas, coal, titanium, zirconium, etc. Jute is the main source of economic resources in Bangladesh. Bangladesh is one of the least developed countries in the world and the most populous country with the highest population density in the world."
        } else if imageName == "Bhutan" {
            detailTextView.text = "The Kingdom of Bhutan (Tibetan Pinyin: Zhugyü), referred to as “Bhutan”, is located on the southern slope of the eastern section of the Himalayas between China and India (the southern part of the Qinghai-Tibet Plateau). The area is 38,400 square kilometers and the population is 783,689 (December 2016). Bhutan has been a Tubo tribe since the 8th century. In the 9th century, Bhutan was an independent tribe. In 1772, the British invaded Bhutan. In 1865, the United Kingdom forced Bhutan to cede the territory of about 2,000 square kilometers east of the Tsit River, including Kalimpong, through the Sin Chula Treaty. In 1907, the Kingdom of Bhutan was established, and Uyan Wangchuk became a hereditary king. In August 1949, India and Bhutan signed the Treaty of Permanent Peace and Friendship, which stipulated that Bhutan’s foreign relations accepted India’s “guidance”. In 1971 became a member of the United Nations. The Bhutanese are the main ethnic groups of Bhutan, and the Western Bhutanese Zongka and English are official terms. Bhutan is the last country in the world to open television and networks. Although Bhutan is one of the least developed countries, it is one of the countries with the highest happiness index in the world. In the “Global Happy Country Ranking” released in 2006, Bhutan ranked eighth and ranked first in Asia."
        } else if imageName == "Lran" {
            detailTextView.text = "Islamic Republic of Iran (English: Islamic Republic of Iran, Persian: جمهوری اسلامی ایران), referred to as Iran. Located in West Asia, it is a Middle Eastern country. It borders Pakistan and Afghanistan to the east, Turkmenistan, Northwest Azerbaijan and Armenia, and Turkey and Iraq to the west. The north central is close to the Caspian Sea, south to the Persian Gulf and the Arabian Sea. The land area is about 1,648,195 square kilometers, ranking 18th in the world. Iran is an ancient civilization. In 550 BC, the first empire of the world's history spanning the three continents of Europe, Asia and Africa, the Persian Empire, was established. The Resting Empire was established in 247 BC, and was invaded by different aliens after the 7th century. In the early 18th century, Nadirsha overthrew the foreign rule and established the Afsal dynasty. Since the late 19th century, British and Russian forces have continued to invade. The Pahlavi dynasty was established in 1925. The Republic was established in 1979. The system of administration and teaching. Iran is a founding member of the United Nations and a member of the Non-Aligned Movement (OIC) and the Organization of Petroleum Exporting Countries (OPEC). Iran is one of the major economies in Asia and has strong economic strength. The Iranian economy is dominated by the oil exploitation industry. It is a world oil and gas power. It is located in the Middle East, where the world's oil and gas are the most abundant. Oil exports are the economic lifeline, and oil production capacity and oil export volume are ranked fourth and second respectively in the world. Is a member of the Organization of Petroleum Exporting Countries. Iran's petrochemical, steel, and automobile manufacturing industries are well developed, as well as the electronics industry, the nuclear industry, and the computer hardware and software industry. On July 14, 2015, after years of arduous negotiations, the final stage of negotiations on the Iranian nuclear issue finally reached a historic comprehensive agreement. Iran promised never to seek nuclear weapons and praised the Iranian nuclear agreement as a historic moment. On September 24, 2017, US President Trump signed the latest travel ban, and Iran is on the new travel ban list."
        } else if imageName == "Maldives" {
            detailTextView.text = "The Republic of Maldives (formerly known as the Maldives Islands), an archipelago country on the Indian Ocean. It is about 600 km south of India and about 750 km southwest of Sri Lanka. Twenty-six natural atolls and 1,192 coral islands are distributed in 90,000 square kilometers of seas, of which about 200 are inhabited. With a land area of 298 square kilometers, it is the smallest country in Asia. The northeast of the Maldives is 675 kilometers away from Sri Lanka, and the northern part is about 113 kilometers away from the island of Minico in India. The equatorial strait and the first half of the strait in the south of the Maldives are the main means of maritime traffic. On August 30, 2018, the opening ceremony of the Maldives Sino-Malaysia Friendship Bridge project was held. Maldivian President Yamin and Wang Xiaotao, representative of the Chinese government and director of the National Development Cooperation Agency, jointly unveiled the opening of the bridge."
        } else if imageName == "Nepal" {
            detailTextView.text = "Federal Democratic Republic of Nepal (referred to as Nepal). The Himalayas are the natural borders of China and Nepal. Including Everest, there are eight of the world's top ten peaks on the Sino-Nepalese border. The total area of ​​the country is 147,181 square kilometers, and the total population in 2016 is about 28.98 million. Nepal is an inland mountain country in South Asia, located in the southern foothills of the Himalayas, bordering China to the north and the other three sides bordering India. The country is divided into three climatic zones: the northern high mountain, the central temperate zone and the southern subtropical zone. The northern minimum winter temperature is -41 °C, and the southern summer maximum temperature is 45 °C. In history, Nepal was attached to the Qing Dynasty in China in 1791, and it belongs to China. At the beginning of the 13th century, the Mala Dynasty rose and vigorously promoted Hinduism. In 1768, the Shah Dynasty rose and unified the country. In 1846, the Lana family relied on Britain to support the seizure of military and political power, and was given the status of a hereditary prime minister. In 1950, the Nigerian people set off a campaign against the dictatorship of the Rana family. King Tribhuvan restored the kingship, ending the Rana family rule and implementing the constitutional monarchy. In 1960, King Mahendra banned political parties and implemented a non-partisan parliamentary system. In 1990, a large-scale peoples movement broke out in Nepal, and King Bandra was forced to restore constitutional monarchy. In 2001, King Birendra was killed in the royal bloody case, and his brother Gianandra was succeeded. In 2005, Jia was pro-government after dissolving the government. The main political parties formed a seven-party alliance, joined forces with the Communist Party of Nepal (Maoist) to oppose the king, and in 2006 passed the second peoples movement to overthrow the kings rule. In 2008, Nigeria held a Constituent Assembly election, and the Constituent Assembly, which was elected after the election, announced the establishment of the Federal Democratic Republic of Nepal. Nepal is a multi-ethnic, multi-religious, multi-name, multi-lingual country. Nepalese is its national language and the upper class is general English. 86.2% of residents believe in Hinduism, 7.8% believe in Buddhism, 3.8% believe in Islam, and 2.2% believe in other religions."
        } else if imageName == "Sri_Lanka" {
            detailTextView.text = "Sri Lanka, the full name of The Democratic Socialist Republic of Sri Lanka, formerly known as Ceylon, is a tropical island country located on the Indian Ocean and one of the Commonwealth countries. In ancient China, it was once called the Lion Kingdom, the Teacher State, and Sinhala. Sri Lanka’s economy is dominated by agriculture, and the country’s most important export is Ceylon black tea. The country is also one of the world's three major tea-producing countries, so the domestic economy is deeply affected by the situation of tea production. In the process of liberalization, the growth rate continues to accelerate. Sri Lanka's biggest advantage lies in mining and geographical location. It is a gem-rich island, the world's top five gemstone producing countries, known as the jewel island. Therefore, in the early stage of the economy, mining has given it many initial development advantages. The annual export of gemstones can reach 500 million US dollars, and rubies, sapphires and cat eyes are the most famous. In Sinhalese, Sri Lanka means “land of happiness” or “land of light and richness”. It has the reputation of “gem kingdom” and “the pearl of the Indian Ocean” and is considered by Marco Polo to be the most beautiful island. Sri Lanka has a long history of international participation, is a founding member of the South Asian Association for Regional Cooperation and a member of the Commonwealth, G77, the Non-Aligned Movement and the United Nations. It is still the only South Asian country that has been rated as “high” in the Human Development Index. On March 6, 2018, President Sirisena and the Cabinet decided that the state would enter a state of emergency from March 6 for a period of 10 days. On March 7, the Sri Lankan government ordered telecommunications service providers to block some social networks."
        } /*else if imageName == "Kazakhstan" {
            detailTextView.text = " Republic of Kazakhstan is the world's largest landlocked country, and the ninth largest in the world, with an area of 2,724,900 square kilometres (1,052,100 sq mi). It is a transcontinental country largely located in Asia; the most western parts are in Europe. Kazakhstan is the dominant nation of Central Asia economically, generating 60% of the region's GDP, primarily through its oil and gas industry. It also has vast mineral resources. Kazakhstan is officially a democratic, secular, unitary, constitutional republic with a diverse cultural heritage. Kazakhstan shares borders with Russia, China, Kyrgyzstan, Uzbekistan, and Turkmenistan, and also adjoins a large part of the Caspian Sea. The terrain of Kazakhstan includes flatlands, steppe, taiga, rock canyons, hills, deltas, snow-capped mountains, and deserts. Kazakhstan has an estimated 18.3 million people as of 2018. Given its large land area, its population density is among the lowest, at less than 6 people per square kilometre (15 people per sq mi). The capital is Nur-Sultan (until 2019 Astana), where it was moved in 1997 from Almaty, the country's largest city."
        } else if imageName == "Latvia" {
            detailTextView.text = "Republic of Latvia, is a country in the Baltic region of Northern Europe. Since its independence, Latvia has been referred to as one of the Baltic states. It is bordered by Estonia to the north, Lithuania to the south, Russia to the east, and Belarus to the southeast, and shares a maritime border with Sweden to the west. Latvia has 1,957,200 inhabitants and a territory of 64,589 km2 (24,938 sq mi). The country has a temperate seasonal climate"
        } else if imageName == "Liechtenstein" {
            detailTextView.text = "Principality of Liechtenstein is a doubly landlocked German-speaking microstate in Alpine Central Europe. The principality is a constitutional monarchy headed by the Prince of Liechtenstein. Liechtenstein is bordered by Switzerland to the west and south and Austria to the east and north. It is Europe's fourth-smallest country, with an area of just over 160 square kilometres (62 square miles) and a population of 37,877. Divided into 11 municipalities, its capital is Vaduz, and its largest municipality is Schaan. It is also the smallest country to border two countries. Economically, Liechtenstein has one of the highest gross domestic products per person in the world when adjusted for purchasing power parity. It was once known as a billionaire tax haven, but is no longer on any blacklists of uncooperative tax haven countries (see taxation section). An Alpine country, Liechtenstein is mountainous, making it a winter sport destination. The country has a strong financial sector centered in Vaduz. Almost 20,000 people commute to work in Liechtenstein. Liechtenstein is a member of the United Nations, the European Free Trade Association, and the Council of Europe, and although not a member of the European Union, it participates in both the Schengen Area and the European Economic Area. It also has a customs union and a monetary union with Switzerland."
        } else if imageName == "Lithuania" {
            detailTextView.text = "Republic of Lithuania (Lithuanian: Lietuvos Respublika), is a country in the Baltic region of Europe. Lithuania is considered to be one of the Baltic states. It is situated along the southeastern shore of the Baltic Sea, to the east of Sweden and Denmark. It is bordered by Latvia to the north, Belarus to the east and south, Poland to the south, and Kaliningrad Oblast (a Russian exclave) to the southwest. Lithuania has an estimated population of 2.8 million people as of 2019, and its capital and largest city is Vilnius. Other major cities are Kaunas and Klaipėda. Lithuanians are Baltic people. The official language, Lithuanian, along with Latvian, is one of only two living languages in the Baltic branch of the Indo-European language family."
        } else if imageName == "Luxembourg" {
            detailTextView.text = "Grand Duchy of Luxembourg, is a small landlocked country in western Europe. It is bordered by Belgium to the west and north, Germany to the east, and France to the south. Its capital, Luxembourg City, is one of the three official capitals of the European Union (together with Brussels and Strasbourg) and the seat of the European Court of Justice, the highest judicial authority in the EU. Its culture, people, and languages are highly intertwined with its neighbours, making it essentially a mixture of French and German cultures, as evident by the nation's three official languages: French, German, and the national language, Luxembourgish. The repeated invasions by Germany, especially in World War II, resulted in the country's strong will for mediation between France and Germany and, among other things, led to the foundation of the European Union. With an area of 2,586 square kilometres (998 sq mi), it is one of the smallest sovereign states in Europe. In 2018, Luxembourg had a population of 602,005, which makes it one of the least-populous countries in Europe, but by far the one with the highest population growth rate. Foreigners account for nearly half of Luxembourg's population. As a representative democracy with a constitutional monarch, it is headed by Grand Duke Henri and is the world's only remaining grand duchy. Luxembourg is a developed country, with an advanced economy and one of the world's highest GDP (PPP) per capita. The City of Luxembourg with its old quarters and fortifications was declared a UNESCO World Heritage Site in 1994 due to the exceptional preservation of the vast fortifications and the old city."
        } else if imageName == "Macedonia" {
            detailTextView.text = "Republic of North Macedonia, is a country in the Balkan Peninsula in Southeast Europe. It is one of the successor states of the former Yugoslavia, from which it declared independence in September 1991 under the name Republic of Macedonia. The country became a member of the United Nations in April 1993, but as a result of a dispute with Greece over the name, it was admitted under the provisional description the former Yugoslav Republic of Macedonia (abbreviated as FYR Macedonia and FYROM), a term that was also used by some other international organisations. In June 2018, Macedonia and Greece resolved the conflict with an agreement that the country should rename itself Republic of North Macedonia. This renaming came into effect in February 2019, with a several-months-long transition for passports, licence plates, currency, customs, border signs, and government websites, among other things"
        } else if imageName == "Malta" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Republic of Malta (Maltese: Repubblika ta' Malta), is a Southern European island country consisting of an archipelago in the Mediterranean Sea. It lies 80 km (50 mi) south of Italy, 284 km (176 mi) east of Tunisia, and 333 km (207 mi) north of Libya. With a population of about 475,000 over an area of 316 km2 (122 sq mi),[3] Malta is the world's tenth smallest and fifth most densely populated country. Its capital is Valletta, which is the smallest national capital in the European Union by area at 0.8 km². The official languages are Maltese and English, with Maltese officially recognised as the national language and the only Semitic language in the European Union. Malta has been inhabited since approximately 5900 BC. Its location in the centre of the Mediterranean has historically given it great strategic importance as a naval base, with a succession of powers having contested and ruled the islands, including the Phoenicians and Carthaginians, Romans, Greeks, Arabs, Normans, Aragonese, Knights of St. John, French, and British. Most of these foreign influences have left some sort of mark on the country's ancient culture."
        } else if imageName == "Moldova" {
            detailTextView.text = "Republic of Moldova, is a landlocked country in Eastern Europe, bordered by Romania to the west and Ukraine to the north, east, and south.[16] The capital city is Chișinău. Most of the Moldovan territory was a part of the Principality of Moldavia from the 14th century until 1812, when it was ceded to the Russian Empire by the Ottoman Empire (to which Moldavia was a vassal state) and became known as Bessarabia. In 1856, southern Bessarabia was returned to Moldavia, which three years later united with Wallachia to form Romania, but Russian rule was restored over the whole of the region in 1878. During the 1917 Russian Revolution, Bessarabia briefly became autonomous and then the independent Moldavian Democratic Republic until it was integrated into Romania in 1918 following a vote of its assembly. The decision was disputed by Soviet Russia, which in 1924 decided the establishment, within the Ukrainian SSR, of a Moldavian autonomous republic (MASSR) on partial Moldovan-inhabited territories to the east of the Dniester. In 1940, as a consequence of the Molotov–Ribbentrop Pact, Romania was compelled to cede Bessarabia to the Soviet Union, leading to the creation of the Moldavian Soviet Socialist Republic (Moldavian SSR), which included the greater part of Bessarabia and the westernmost strip of the former MASSR."
        } else if imageName == "Monaco" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Principality of Monaco, is a sovereign city-state, country, and microstate on the French Riviera in Western Europe. France borders the country on three sides while the other side borders the Mediterranean Sea. Monaco is about 15 km from the state border with Italy. Monaco has an area of 2.020 km2 (0.780 sq mi), making it the second-smallest country in the world after the Vatican. Its population was about 38,400 based on the last census of 2016. With 19,009 inhabitants per km², it is the most densely-populated sovereign state in the world. Monaco has a land border of 5.47 km (3.40 mi), a coastline of 3.83 km (2.38 mi), and a width that varies between 1,700 and 349 m (5,577 and 1,145 ft). The highest point in the country is a narrow pathway named Chemin des Révoires on the slopes of Mont Agel, in the Les Révoires Ward, which is 161 metres (528 feet) above sea level. Monaco's most populous Quartier is Monte Carlo and the most populous Ward is Larvotto/Bas Moulins. Through land reclamation, Monaco's land mass has expanded by 20 percent; in 2005, it had an area of only 1.974 km2 (0.762 sq mi). Monaco is known to be the most expensive and the wealthiest place on Earth, Vatican City excluded, due to its tax laws. In 2014, it was noted that about 30% of the population was made up of millionaires."
        } else if imageName == "Montenegro" {
            detailTextView.text = "Montenegro is a country in Southeast Europe on the Adriatic Sea. It borders Bosnia and Herzegovina to the northwest; Serbia and Kosovo to the east, Albania to the south and Croatia to the west. Montenegro has an area of 13,812 square kilometres and a population of 620,079 (2011 census). Its capital Podgorica is one of the twenty-three municipalities in the country. Cetinje is designated as the Old Royal Capital."
        } else if imageName == "Netherlands" {
            detailTextView.text = "The Netherlands, also commonly known as Holland, is a country located mainly in Northwestern Europe. The European portion of the Netherlands consists of twelve separate provinces that border Germany to the east, Belgium to the south, and the North Sea to the northwest, with maritime borders in the North Sea with Belgium, Germany and the United Kingdom. Together with three island territories in the Caribbean Sea—Bonaire, Sint Eustatius and Saba—it forms a constituent country of the Kingdom of the Netherlands. The official language is Dutch, but a secondary official language in the province of Friesland is West Frisian. The six largest cities in the Netherlands are Amsterdam, Rotterdam, The Hague, Utrecht, Eindhoven and Tilburg. Amsterdam is the country's capital, while The Hague holds the seat of the States General, Cabinet and Supreme Court. The Port of Rotterdam is the largest port in Europe, and the largest in any country outside Asia. The country is a founding member of the EU, Eurozone, G10, NATO, OECD and WTO, as well as a part of the Schengen Area and the trilateral Benelux Union. It hosts several intergovernmental organisations and international courts, many of which are centered in The Hague, which is consequently dubbed 'the world's legal capital'"
        } else if imageName == "Norway" {
            detailTextView.text = "Kingdom of Norway, is a Nordic country in Northern Europe whose territory comprises the western and northernmost portion of the Scandinavian Peninsula; the remote island of Jan Mayen and the archipelago of Svalbard are also part of the Kingdom of Norway. The Antarctic Peter I Island and the sub-Antarctic Bouvet Island are dependent territories and thus not considered part of the kingdom. Norway also lays claim to a section of Antarctica known as Queen Maud Land. Norway has a total area of 385,207 square kilometres (148,729 sq mi) and a population of 5,312,300 (as of August 2018). The country shares a long eastern border with Sweden (1,619 km or 1,006 mi long). Norway is bordered by Finland and Russia to the north-east, and the Skagerrak strait to the south, with Denmark on the other side. Norway has an extensive coastline, facing the North Atlantic Ocean and the Barents Sea. Harald V of the House of Glücksburg is the current King of Norway. Erna Solberg has been prime minister since 2013 when she replaced Jens Stoltenberg. A unitary sovereign state with a constitutional monarchy, Norway divides state power between the parliament, the cabinet and the supreme court, as determined by the 1814 constitution. The kingdom was established in 872 as a merger of a large number of petty kingdoms and has existed continuously for 1,147 years. From 1537 to 1814, Norway was a part of the Kingdom of Denmark-Norway, and from 1814 to 1905, it was in a personal union with the Kingdom of Sweden. Norway was neutral during the First World War. Norway remained neutral until April 1940 when the country was invaded and occupied by Germany until the end of Second World War."
        } else if imageName == "Poland" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Republic of Poland, is a country located in Central Europe. It is divided into 16 administrative subdivisions, covering an area of 312,696 square kilometres (120,733 sq mi), and has a largely temperate seasonal climate. With a population of approximately 38.5 million people, Poland is the sixth most populous member state of the European Union. Poland's capital and largest metropolis is Warsaw. Other major cities include Kraków, Łódź, Wrocław, Poznań, Gdańsk, and Szczecin. Poland is bordered by the Baltic Sea, Russia's Kaliningrad Oblast and Lithuania to the north, Belarus and Ukraine to the east, Slovakia and Czech Republic, to the south, and Germany to the west."
        } else if imageName == "Portugal" {
            detailTextView.text = "Portuguese Republic is a country located mostly on the Iberian Peninsula in southwestern Europe. It is the westernmost sovereign state of mainland Europe, being bordered to the west and south by the Atlantic Ocean and to the north and east by Spain. Its territory also includes the Atlantic archipelagos of the Azores and Madeira, both autonomous regions with their own regional governments."
        } else if imageName == "Romania" {
            detailTextView.text = "Romania is a country located at the crossroads of Central, Eastern, and Southeastern Europe. It borders the Black Sea to the southeast, Bulgaria to the south, Ukraine to the north, Hungary to the west, Serbia to the southwest, and Moldova to the east. It has a predominantly temperate-continental climate. With a total area of 238,397 square kilometres (92,046 sq mi), Romania is the 12th largest country and also the 7th most populous member state of the European Union, having almost 20 million inhabitants. Its capital and largest city is Bucharest, and other major urban areas include Cluj-Napoca, Timișoara, Iași, Constanța, Craiova, and Brașov. The River Danube, Europe's second-longest river, rises in Germany's Black Forest and flows in a general southeast direction for 2,857 km (1,775 mi), coursing through ten countries before emptying into Romania's Danube Delta. The Carpathian Mountains, which cross Romania from the north to the southwest, include Moldoveanu Peak, at an altitude of 2,544 m (8,346 ft)."
        } else if imageName == "Russia" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Russian Federation, is a transcontinental country in Eastern Europe and North Asia. At 17,125,200 square kilometres (6,612,100 sq mi), Russia is by a considerable margin the largest country in the world by area, covering more than one-eighth of the Earth's inhabited land area, and the ninth most populous, with about 146.79 million people as of 2019, including Crimea. About 77% of the population live in the western, European part of the country. Russia's capital, Moscow, is one of the largest cities in the world and the second largest city in Europe; other major cities include Saint Petersburg, Novosibirsk, Yekaterinburg and Nizhny Novgorod. Extending across the entirety of Northern Asia and much of Eastern Europe, Russia spans eleven time zones and incorporates a wide range of environments and landforms. From northwest to southeast, Russia shares land borders with Norway, Finland, Estonia, Latvia, Lithuania and Poland (both with Kaliningrad Oblast), Belarus, Ukraine, Georgia, Azerbaijan, Kazakhstan, China, Mongolia and North Korea. It shares maritime borders with Japan by the Sea of Okhotsk and the U.S. state of Alaska across the Bering Strait. However, Russia recognises two more countries that border it, Abkhazia and South Ossetia, both of which are internationally recognized as parts of Georgia."
        } else if imageName == "San Marino" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Republic of San Marino, also known as the Most Serene Republic of San Marino, is an enclaved small-sized country, surrounded by Italy, situated on the Italian Peninsula on the northeastern side of the Apennine Mountains. Its size is just over 61 km2 (24 sq mi), with a population of 33,562. Its capital is the City of San Marino and its largest settlement is Dogana in the municipality of Serravalle. San Marino has the smallest population of all the members of the Council of Europe. With Italian being the official language, along with strong financial and ethno-cultural connections, San Marino maintains close ties to its much larger neighbour; it is located close to the riviera of Rimini, one of Italy's main coastal resort areas."
        } else if imageName == "Serbia" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Republic of Serbia, is a country situated at the crossroads of Central and Southeast Europe in the southern Pannonian Plain and the central Balkans. It borders Hungary to the north, Romania to the northeast, Bulgaria to the southeast, North Macedonia to the south, Croatia and Bosnia and Herzegovina to the west, and Montenegro to the southwest. The country claims a border with Albania through the disputed territory of Kosovo. Serbia's population numbers approximately seven million,[8] most of whom are Orthodox Christians. Its capital, Belgrade, ranks among the oldest and largest citiеs in southeastern Europe."
        } else if imageName == "Slovakia" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Slovak Republic is a landlocked country in Central Europe. It is bordered by Poland to the north, Ukraine to the east, Hungary to the south, Austria to the west, and the Czech Republic to the northwest. Slovakia's territory spans about 49,000 square kilometres (19,000 sq mi) and is mostly mountainous. The population is over 5.4 million and consists mostly of Slovaks. The capital and largest city is Bratislava, and the second-largest city is Košice. The official language is Slovak."
        } else if imageName == "Slovenia" {
            detailImageView.layer.borderColor = #colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)
            detailTextView.text = "Republic of Slovenia, is a country located in southern Central Europe at a crossroads of important European cultural and trade routes. It is bordered by Italy to the west, Austria to the north, Hungary to the northeast, Croatia to the southeast, and the Adriatic Sea to the southwest. It covers 20,273 square kilometers (7,827 sq mi) and has a population of 2.07 million. One of the successor states of the former Yugoslavia, Slovenia is a parliamentary republic and a member of the United Nations, of the European Union, and of NATO. The capital and largest city is Ljubljana. Slovenia has a mostly mountainous terrain with a mainly continental climate, with the exception of the Slovene Littoral, which has a sub-Mediterranean climate, and of the northwest, which has an Alpine climate. Additionally, the Dinaric Alps and the Pannonian Plain meet on the territory of Slovenia. The country, marked by a significant biological diversity, is one of the most water-rich in Europe, with a dense river network, a rich aquifer system, and significant karst underground watercourses. Over half of the territory is covered by forest. The human settlement of Slovenia is dispersed and uneven."
        } else if imageName == "Spain" {
            detailTextView.text = "Kingdom of Spain is a country mostly located in Europe. Its continental European territory is situated on the Iberian Peninsula. Its territory also includes two archipelagoes: the Canary Islands off the coast of Africa, and the Balearic Islands in the Mediterranean Sea. The African enclaves of Ceuta, Melilla, and Peñón de Vélez de la Gomera make Spain the only European country to have a physical border with an African country (Morocco). Several small islands in the Alboran Sea are also part of Spanish territory. The country's mainland is bordered to the south and east by the Mediterranean Sea except for a small land boundary with Gibraltar; to the north and northeast by France, Andorra, and the Bay of Biscay; and to the west and northwest by Portugal and the Atlantic Ocean. With an area of 505,990 km2 (195,360 sq mi), Spain is the largest country in Southern Europe, the second largest country in Western Europe and the European Union, and the fourth largest country in the European continent. By population, Spain is the sixth largest in Europe and the fifth in the European Union. Spain's capital and largest city is Madrid; other major urban areas include Barcelona, Valencia, Seville, Málaga and Bilbao. Modern humans first arrived in the Iberian Peninsula around 35,000 years ago. Iberian cultures along with ancient Phoenician, Greek, Celtic and Carthaginian settlements developed on the peninsula until it came under Roman rule around 200 BCE, after which the region was named Hispania, based on the earlier Phoenician name Sp(a)n or Spania. At the end of the Western Roman Empire the Germanic tribal confederations migrated from Central Europe, invaded the Iberian peninsula and established relatively independent realms in its western provinces, including the Suebi, Alans and Vandals. Eventually, the Visigoths would forcibly integrate all remaining independent territories in the peninsula, including Byzantine provinces, into the Kingdom of Toledo, which more or less unified politically, ecclesiastically and legally all the former Roman provinces or successor kingdoms of what was then documented as Hispania."
        } else if imageName == "Sweden" {
            detailTextView.text = "Kingdom of Sweden, is a Scandinavian Nordic country in Northern Europe. It borders Norway to the west and north and Finland to the east, and is connected to Denmark in the southwest by a bridge-tunnel across the Öresund, a strait at the Swedish-Danish border. At 450,295 square kilometres (173,860 sq mi), Sweden is the largest country in Northern Europe, the third-largest country in the European Union and the fifth largest country in Europe by area. Sweden has a total population of 10.2 million of which 2.5 million have a foreign background. It has a low population density of 22 inhabitants per square kilometre (57/sq mi). The highest concentration is in the southern half of the country."
        } else if imageName == "Switzerland" {
            detailTextView.text = "Swiss Confederation, is a sovereign state situated in the confluence of western, central, and southern Europe. It is a federal republic composed of 26 cantons, with federal authorities seated in Bern. Switzerland is a landlocked country bordered by Italy to the south, France to the west, Germany to the north, and Austria and Liechtenstein to the east. It is geographically divided between the Alps, the Swiss Plateau and the Jura, spanning a total area of 41,285 km2 (15,940 sq mi). While the Alps occupy the greater part of the territory, the Swiss population of approximately 8.5 million is concentrated mostly on the plateau, where the largest cities are located, among them the two global cities and economic centres of Zürich and Geneva."
        } else if imageName == "Turkey" {
            detailTextView.text = "Republic of Turkey, is a transcontinental country located mainly in Western Asia, with a smaller portion on the Balkan Peninsula in Southeast Europe. East Thrace, located in Europe, is separated from Anatolia by the Sea of Marmara, the Bosphorous strait and the Dardanelles (collectively called the Turkish Straits). Turkey is bordered by Greece and Bulgaria to its northwest; Georgia to its northeast; Armenia, the Azerbaijani exclave of Nakhchivan and Iran to the east; and Iraq and Syria to the south. Istanbul is the largest city, but more central Ankara is the capital. Approximately 70 to 80 per cent of the country's citizens identify as Turkish. Kurds are the largest minority; the size of the Kurdish population is a subject of dispute with estimates placing the figure at anywhere from 12 to 25 per cent of the population."
        } else if imageName == "Ukraine" {
            detailTextView.text = "Ukraine, is a country in Eastern Europe. Excluding Crimea, Ukraine has a population of about 42.5 million, making it the 32nd most populous country in the world. Its capital and largest city is Kiev. Ukrainian is the official language and its alphabet is Cyrillic. The dominant religions in the country are Eastern Orthodoxy and Greek Catholicism. Ukraine is currently in a territorial dispute with Russia over the Crimean Peninsula, which Russia annexed in 2014. Including Crimea, Ukraine has an area of 603,628 km2 (233,062 sq mi), making it the largest country entirely within Europe and the 46th largest country in the world."
        } else if imageName == "United Kingdom" {
            detailTextView.text = "United Kingdom of Great Britain and Northern Ireland, and sometimes referred to as Britain, is a sovereign country located off the north-western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north-eastern part of the island of Ireland, and many smaller islands. Northern Ireland is the only part of the United Kingdom that shares a land border with another sovereign state, the Republic of Ireland. Apart from this land border, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the south-west, giving it the 12th-longest coastline in the world. The Irish Sea lies between Great Britain and Ireland. With an area of 242,500 square kilometres (93,600 sq mi), the United Kingdom is the 78th-largest sovereign state in the world. It is also the 22nd-most populous country, with an estimated 66.0 million inhabitants in 2017."
        }
 */
        
        
        
        
    }//end of viewDidload
    
    // MARK: detailTextView top alighment
    override func viewDidLayoutSubviews() {
        detailTextView.setContentOffset(.zero, animated: false)
    }
    
    override var prefersStatusBarHidden: Bool {
        return true
    }
    
} //end of class

